### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ghost** [sherinkurian/mani#10]
Hello,
I'm just trying out Mani and not getting very far:

```
Traceback (most recent call last):
  File "E:\Python\Timer_test.py", line 1, in <module>
    from mani import Mani
  File "C:\Python36\lib\site-packages\mani\__init__.py", line 7, in <module>
    from .scheduler import Scheduler
  File "C:\Python36\lib\site-packages\mani\scheduler.py", line 16, in <module>
    class Scheduler:
  File "C:\Python36\lib\site-packages\mani\scheduler.py", line 27, in Scheduler
    signal.SIGQUIT
AttributeError: module 'signal' has no attribute 'SIGQUIT'
```

Can you help please?

**Comment by mmontagna** [comment]
Are you on a windows machine by any chance?
